# https://github.com/helix-editor/helix/blob/master/helix-term/src/commands.rs

theme = "monokai_pro_dark"

[editor]
true-color = true
color-modes = true


[keys.insert]
"A-b" = "move_prev_long_word_start"
"A-f" = "move_next_long_word_start"
"A-n" = "goto_next_paragraph"
"A-p" = "goto_prev_paragraph"
"C-a" = "goto_line_start"
"C-e" = "goto_line_end"


"A-o" = ["rotate_view", "insert_mode"]
"A-s" = "rsearch"
"A-x" = "command_mode"
 
"C-g" = "insert_mode"
"C-o" = ["rotate_view", "insert_mode"]
"C-r" = "redo"
"C-s" = "search"
"C-x" = "normal_mode"
"C-y" = "paste_after"

"C-_" = "undo"

"C-space" = "select_mode"

"C-left" = ["jump_view_left", "insert_mode"]
"C-down" = ["jump_view_down", "insert_mode"]
"C-up" = ["jump_view_up", "insert_mode"]
"C-right" = ["jump_view_right", "insert_mode"]

"C-c" = { "l" = "goto_line", "d" = "goto_definition", "y" = "goto_type_definition", "x" = "goto_reference", "s" = "symbol_picker", "w" = "workspace_symbol_picker" }


[keys.normal]
"A-b" = ["move_prev_long_word_start", "insert_mode"]
"A-f" = ["move_next_long_word_start", "insert_mode"]
"A-n" = ["goto_next_paragraph", "insert_mode"]
"A-p" = ["goto_prev_paragraph", "insert_mode"]
"C-a" = ["goto_line_start", "insert_mode"]
"C-e" = ["goto_line_end", "insert_mode"]

"A-x" = "command_mode"
"A-o" = ["rotate_view", "insert_mode"]

"C-b" = ["buffer_picker", "insert_mode"]
"C-c" = ":quit"
"C-f" = ["file_picker", "insert_mode"]
"C-k" = ["kill_to_line_end", "insert_mode"]
"C-g" = "insert_mode"
"C-o" = ["rotate_view", "insert_mode"]
"C-r" = ["redo", "insert_mode"]
"C-s" = [":write", "insert_mode"]
"C-x" = "normal_mode"
"C-y" = ["paste_after", "insert_mode"]

"C-_" = ["undo", "insert_mode"]

"C-space" = "select_mode"

"b" = ["goto_next_buffer", "insert_mode"]
"c" = ":quit"
"h" = ["hsplit", "insert_mode"]
"k" = ":buffer-close"
"o" = ["rotate_view", "insert_mode"]
"p" = ["wonly", "insert_mode"]
"s" = [":write", "insert_mode"]
"v" = ["vsplit", "insert_mode"]

"left" = ["move_char_left", "insert_mode"]
"down" = ["move_line_down", "insert_mode"]
"up" = ["move_line_up", "insert_mode"]
"right" = ["move_char_right", "insert_mode"]

"C-left" = ["jump_view_left", "insert_mode"]
"C-down" = ["jump_view_down", "insert_mode"]
"C-up" = ["jump_view_up", "insert_mode"]
"C-right" = ["jump_view_right", "insert_mode"]

"C-c" = { "l" = "goto_line", "d" = "goto_definition", "y" = "goto_type_definition", "x" = "goto_reference" }


[keys.select]
"A-b" = "move_prev_long_word_start"
"A-f" = "move_next_long_word_start"
"A-n" = "goto_next_paragraph"
"A-p" = "goto_prev_paragraph"
"C-a" = "goto_line_start"
"C-e" = "goto_line_end"


"space" = ["yank", "insert_mode"]
"A-w" = ["yank", "insert_mode"]
"C-w" = ["delete_selection", "insert_mode"]
"C-g" = "insert_mode"
