# https://github.com/helix-editor/helix/blob/master/helix-term/src/commands.rs

theme = "monokai_pro_dark"

[editor]
true-color = true

[keys.insert]
"A-b" = "move_prev_long_word_start"
"A-f" = "move_next_long_word_start"
"A-n" = "goto_next_paragraph"
"A-p" = "goto_prev_paragraph"
"A-x" = "command_mode"
"C-o" = ["rotate_view", "insert_mode"]
"A-o" = ["rotate_view", "insert_mode"]
"C-g" = "insert_mode"
"C-space" = "select_mode"
"C-y" = "paste_after"
"C-x" = "normal_mode"

[keys.normal]
"A-b" = "move_prev_long_word_start"
"A-f" = "move_next_long_word_start"
"A-n" = "goto_next_paragraph"
"A-p" = "goto_prev_paragraph"
"A-x" = "command_mode"
"C-b" = "buffer_picker"
"C-c" = ":quit"
"C-f" = ["file_picker", "insert_mode"]
"C-k" = ["kill_to_line_end", "insert_mode"]
"C-g" = "insert_mode"
"C-o" = ["rotate_view", "insert_mode"]
"A-o" = ["rotate_view", "insert_mode"]
"C-s" = [":write", "insert_mode"]
"C-space" = "select_mode"
"C-x" = "normal_mode"
"C-y" = ["paste_after", "insert_mode"]
"b" = "goto_next_buffer"
"h" = "hsplit"
"v" = "vsplit"
"o" = ["rotate_view", "insert_mode"]

[keys.select]
"space" = "yank"
"C-g" = "insert_mode"
